CREATE TABLE books(
    id SERIAL PRIMARY KEY NOT NULL,
    isbn VARCHAR(13) UNIQUE NOT NULL,
    title TEXT NOT NULL,
    author TEXT,
    quantity INT NOT NULL DEFAULT 1
);

CREATE TYPE ROLE AS ENUM ('LIBRARIAN', 'READER');

CREATE TABLE people(
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    role ROLE NOT NULL DEFAULT 'READER',
    email TEXT UNIQUE NOT NULL,
    salt TEXT NOT NULL,
    hash_password TEXT NOT NULL
);

CREATE TABLE loan(
    id SERIAL PRIMARY KEY NOT NULL,
    people_id INT NOT NULL REFERENCES people(id),
    book_id INT NOT NULL REFERENCES books(id),
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    duration INT NOT NULL DEFAULT 15,
    return_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);